### ISSUE TITLE
Handle NonDigit Numeric Values!

### ISSUE THREAD

**Issue by reza-samei** [reza-samei/elasticreporter#6]
Cosider: 'Infinity' It's a numeric value in most programing languages but ES is sensitive to parse this values,
for example in a case of sending a Json containing this: `"KafkaConsumer.records-lag-max": -Infinity` to ES,
it responds with:
```
{
    "error":{"root_cause":[{"type":"mapper_parsin$_exception","reason":"failed to parse"}],
    "type":"mapper_parsing_exception",
    "reason":"failed to parse","caused_by":{
        "type":"json_pa$se_exception",
        "reason":"Non-standard token '-Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@721e357a; line: 1, column: 2042]"
    }},"status":400
}
```

**Comment by reza-samei** [comment]
null could be another possible non-digit value for numeric fields.

**Comment by reza-samei** [comment]
```
2018-06-19 12:39:58,437 DEBUG com.sameei.xtool.elasticreporter.v1.flink.Reporter.CallLogTest-feca28aff5a3958840bee985ee7de4d3-0  - 
Vars, Count: 10, Context: com.sameei.xtool.elasticreporter.v1.flink.Reporter.context.1529395798428
2018-06-19 12:39:58,437 DEBUG com.sameei.xtool.elasticreporter.v1.flink.Reporter.CallLogTest-feca28aff5a3958840bee985ee7de4d3-0  - 
Metrics, Count: 65, Context: com.sameei.xtool.elasticreporter.v1.flink.Reporter.context.1529395798428
2018-06-19 12:39:58,440 WARN  com.sameei.xtool.elasticreporter.v1.flink.Reporter.elastic    - PUT, URL: http://192.168.218.42:9200/
stageflinkd1-task-calllogtest-2018-6/doc/feca28aff5a3958840bee985ee7de4d3-0-single-node-1529395798428, Req(3495): 


{
    "@meta.time.millis": 1529395798428, 
    "@meta.time.formatted": 
    "2018-06-19 08:09:58", "@meta.source.id": "single-node", "numRecordsIn": 0, "numBytesInRemote": 0, 
    "numBytesInLocal": 0, "numRecordsOut": 0, "numBytesOut": 8295, 

"KafkaConsumer.response-rate": 6.195437904815545, "KafkConsumer.fetch-latency-avg": 501.34761904761905, "buffers.outputQueueLength": 0, "KafkaConsumer.sync-rate": 0.0, "KafkaConsumer.ne$
work-io-rate": 12.39087580963109, "KafkaConsumer.request-rate": 6.19561237996001, "buffers.inputQueueLength": 0, "KafkaConsumer.re$
uest-size-max": 114.0, "KafkaConsumer.join-rate": 0.0, "KafkaConsumer.fetch-latency-max": 519.0, "KafkaConsumer.committed-offsets.$
allcmds-2": -915623761776, "KafkaConsumer.fetch-size-avg": 0.0, "KafkaConsumer.join-time-avg": 0.0, "KafkaConsumer.commit-rate": 0$
20558271277810772, "KafkaConsumer.io-wait-time-ns-avg": 4.355593318321513E7, "KafkaConsumer.request-size-avg": 75.27272727272727, $
KafkaConsumer.io-time-ns-avg": 42246.08865248227, "buffers.inPoolUsage": 0.0, "KafkaConsumer.records-per-request-avg": 0.0, "Kafka$
onsumer.current-offsets.callcmds-1": 19, "KafkaConsumer.fetch-rate": 5.998628884826325, "KafkaConsumer.outgoing-byte-rate": 466.36$
6409642626, "KafkaConsumer.commit-latency-max": 5.0, "KafkaConsumer.select-rate": 22.921859759401755, "KafkaConsumer.connection-cr$
ation-rate": 0.0, "KafkaConsumer.join-time-max": 0.0, "KafkaConsumer.sync-time-max": 0.0, "KafkaConsumer.fetch-throttle-time-avg": 
0.0, "KafkaConsumer.assigned-partitions": 3.0, "KafkaConsumer.committed-offsets.callcmds-0": -915623761776, "KafkaConsumer.fetch-t$
rottle-time-max": 0.0, "KafkaConsumer.commit-latency-avg": 4.166666666666667, "KafkaConsumer.current-offsets.callcmds-0": 21, "Kaf$
aConsumer.last-heartbeat-seconds-ago": 1.529395798E9, "KafkaConsumer.incoming-byte-rate": 271.81075753308926, "KafkaConsumer.heart$
eat-rate": 0.0, "KafkaConsumer.fetch-size-max": 0.0, "KafkaConsumer.connection-close-rate": 0.0, "KafkaConsumer.io-wait-ratio": 0.$
983829921155305, "KafkaConsumer.records-lag-max": -Infinity, "KafkaConsumer.sync-time-avg": 0.0, "KafkaConsumer.bytes-consumed-rat$
": 0.0, "KafkaConsumer.records-consumed-rate": 0.0, "buffers.outPoolUsage": 0.0, "KafkaConsumer.heartbeat-response-time-max": -Inf$
nity, "KafkaConsumer.connection-count": 4.0, "KafkaConsumer.committed-offsets.callcmds-1": -915623761776, "KafkaConsumer.io-ratio"$
 9.683589194754525E-4, "KafkaConsumer.current-offsets.callcmds-2": 54, "KafkaConsumer.count": 85.0, 

    "numBytesInRemotePerSecond.cou$t": 0, 
    "numBytesInRemotePerSecond.rate": 0.0, "numBytesOutPerSecond.count": 8295, "numBytesOutPerSecond.rate": 10.5, 
    "numBytesInLo$alPerSecond.count": 0, "numBytesInLocalPerSecond.rate": 0.0, "numRecordsOutPerSecond.count": 0, 
    "numRecordsOutPerSecond.rate": 0.0, "numRecordsInPerSecond.count": 0, "numRecordsInPerSecond.rate": 0.0, 
    "@meta.var.<job_id>": "5d9e2db9da094269c4d66ea5559ddd1e", "@meta.var.<operator_name>": "Source: Custom Source", 
    "@meta.var.<task_name>": "Source: Custom Source", "@meta.var.<tm_id>": "f3db0e90b07e202667591bdf59a9b5f", 
    "@meta.var.<millis>": "1529395798428", "@meta.var.<subtask_index>": "0", 
    "@meta.var.<source_id>": "singe-node", "@meta.var.<job_name>": "CallLogTest", "@meta.var.<host>": "172.16.20.18", 
    "@meta.var.<month>": "6", "@meta.var.<day_of_mnth>": "19", "@meta.var.<year>": "2018", 
    "@meta.var.<task_id>": "feca28aff5a3958840bee985ee7de4d3", "@meta.var.<task_attempt_num>": "0", 
    "@meta.var.<task_attempt_id>": "50dcf1ec7a43b500f1cda59440ef20b9"
}, 

Res(437): {
    "error":{"root_cause":[{"type":"mapper_parsin$_exception","reason":"failed to parse"}],
    "type":"mapper_parsing_exception",
    "reason":"failed to parse","caused_by":{
        "type":"json_pa$se_exception",
        "reason":"Non-standard token '-Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@721e357a; line: 1, column: 2042]"
    }},"status":400
}
2018-06-19 12:39:58,440 WARN  com.sameei.xtool.elasticreporter.v1.flink.Reporter            - Apply, Failed, GroupedMetrics: com.s$
meei.xtool.elasticreporter.v1.flink.Reporter.CallLogTest-feca28aff5a3958840bee985ee7de4d3-0, Context: com.sameei.xtool.elasticrepo$
ter.v1.flink.Reporter.context.1529395798428, DateTime: 2018-06-19 08:09:58, Index: stageflinkd1-task-calllogtest-2018-6, Doc: feca$
8aff5a3958840bee985ee7de4d3-0-single-node-1529395798428, Failure: Put Failure, Unexpected ResponseCode: 400
com.sameei.xtool.elasticreporter.v1.elastic.Elastic$PutException: Put Failure, Unexpected ResponseCode: 400
        at com.sameei.xtool.elasticreporter.v1.elastic.Elastic$$anonfun$put$1.apply$mcV$sp(Elastic.scala:70)
        at com.sameei.xtool.elasticreporter.v1.elastic.Elastic$$anonfun$put$1.apply(Elastic.scala:35)
        at com.sameei.xtool.elasticreporter.v1.elastic.Elastic$$anonfun$put$1.apply(Elastic.scala:35)
        at scala.util.Try$.apply(Try.scala:192)
        at com.sameei.xtool.elasticreporter.v1.elastic.Elastic.put(Elastic.scala:35)
        at com.sameei.xtool.elasticreporter.v1.elastic.Reporter.apply(Reporter.scala:56)
        at com.sameei.xtool.elasticreporter.v1.elastic.Reporter$$anonfun$applyAll$1.apply(Reporter.scala:69)
        at com.sameei.xtool.elasticreporter.v1.elastic.Reporter$$anonfun$applyAll$1.apply(Reporter.scala:69)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at com.sameei.xtool.elasticreporter.v1.elastic.Reporter.applyAll(Reporter.scala:69)
        at com.sameei.xtool.elasticreporter.v1.flink.lego.ReporterForMultipleGroups$class.report(ReporterForMultipleGroups.scala:8$
```

**Comment by reza-samei** [comment]
0.2 Done
